db:
  username: postgres
  password: root
  driver: org.postgresql.Driver
  url: postgres:5432
  host: localhost
  pool:
    size: 12
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 20
      timeout: 40

logging:
  level:
    root: WARN
    org.timowa.spring.database.repository.pool: INFO
#  file:
#    name: log
#    path: /