db: 
  username: postgres
  password: root
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 20
      timeout: 40