db:
  username: postgres
  password: root
  driver: org.postgresql.Driver
  url: postgres:5432
  host: localhost
  pool:
    size: 12
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 20
      timeout: 40

logging:
  level:
    root: WARN
    org.timowa.spring.database.repository.pool: INFO
#  file:
#    name: log
#    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate:
      show_sql: true
      format_sql: true
    open-in-view: false

app:
  image:
    bucket: images